apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Chart.Name }}-pv
  labels:
    app: {{ .Chart.Name }}
spec:
  capacity:
    storage: {{ .Values.persistentVolume.capacity }}
  accessModes:
{{- range .Values.persistentVolume.accessModes }}
    - {{ . }}
{{- end }}
  hostPath:
    path: {{ .Values.persistentVolume.hostPath }}
  persistentVolumeReclaimPolicy: Retain